sudo: required

#language: php

services:
  - docker
  
branches:
  only: 
    - master
    - staging-ci
    - radioberry-patch-1 

install:
  - git clone https://github.com/radioberry/docker-selenium-grid.git
  - ls
before_script:
#  - docker-compose build
script:
  - docker-compose up -d --scale chrome=10 hub chrome
  - docker-compose ps -q dockerseleniumgrid_hub_1
  - docker-compose ps -q hub
  - docker ps
  - curl --version
  - curl localhost:4444
  - curl localhost:4444/grid/console

after_script:
notifications:
  slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
