sudo: required

#language: php

services:
  - docker
  
branches:
  only: 
    - master
    - staging-ci
    - radioberry-patch-1 

install:
  - git clone https://github.com/radioberry/docker-selenium-grid.git
  - ls
  - docker ps -a
  - docker images
before_script:
  - docker-compose build
  - docker-compose up -d

script:
  - docker images
  - docker ps
  - curl --version
  - curl localhost:4444
  - curl localhost:4444/grid/console

after_script:
  - docker ps -a
notifications:
  slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
