sudo: required

#language: php

services:
  - docker
  
branches:
  only: 
    - master
    - staging-ci

install:
  - git clone https://github.com/radioberry/docker-selenium-grid.git
  - ls
  - docker ps -a

before_script:
  - docker-compose up -d

script:
  - sleep 100
  - docker ps
  - curl --version
  - curl localhost:4444
  - curl localhost:4444/grid/console

after_script:
  - docker images
  
notifications:
  slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
