version: '3'
services:
  hub:
    image: selenium/hub:latest
    ports:
      - '4444:4444'
    restart: always
  chrome:
    image: selenium/node-chrome:3.4.0-einsteinium
    links:
      - hub
    volumes:
      - /dev/crandom:/dev/random
    restart: always
    environment:
     - no_proxy=localhost
     - HUB_PORT_4444_TCP_ADDR=hub
     - HUB_PORT_4444_TCP_PORT=4444
     - HUB_ENV_no_proxy=localhost
  firefox:
    image: selenium/node-firefox:3.4.0-einsteinium
    links:
      - hub
    volumes:
      - /dev/frandom:/dev/random
    restart: always
    environment:
     - no_proxy=localhost
     - HUB_PORT_4444_TCP_ADDR=hub
     - HUB_PORT_4444_TCP_PORT=4444
     - HUB_ENV_no_proxy=localhost
  chrome-vnc:
    image: selenium/node-chrome-debug:3.4.0-einsteinium
    links:
      - hub
    volumes:
      - /dev/cvrandom:/dev/random
    restart: always
    environment:
     - no_proxy=localhost
     - HUB_PORT_4444_TCP_ADDR=hub
     - HUB_PORT_4444_TCP_PORT=4444
     - HUB_ENV_no_proxy=localhost
  firefox-vnc:
    image: selenium/node-firefox-debug:3.4.0-einsteinium
    links:
      - hub
    volumes:
      - /dev/fvrandom:/dev/random
    restart: always
    environment:
     - no_proxy=localhost
     - HUB_PORT_4444_TCP_ADDR=hub
     - HUB_PORT_4444_TCP_PORT=4444
     - HUB_ENV_no_proxy=localhost
